#!/bin/bash
# author: rilysh, license: unlicense

help() {
    echo "
cafe - catfetch utility

usage
-----
[-ra] - random ansi color
[-rb] - random bold color
[-b] - blink
[-h] - help menu (this one)
"
}

has() {
    _cmd=$(command -v "$1") 2>/dev/null || return 1
    [ -x "$_cmd" ] || return 1
}

# Optionally you can bare to execute 2 different commands, as awk is harder, so... 
# awk -F: "NR==2{print $1}" /etc/os-release | sed -E 's/PRETTY_NAME=//' | sed -E 's/["",]//g'
os=$(lsb_release -ds | sed -n 's/PRETTY_NAME=//p' /etc/os-release | sed -E 's/["",]//g')
kernel_ver=$(uname -r)
wm=${WAYLAND_DISPLAY:-$(xprop -id "$(xprop -root _NET_SUPPORTING_WM_CHECK | cut -d' ' -f5)" _NET_WM_NAME | cut -d'"' -f2)}
uptime=$(uptime -p | sed "s/up[[:space:]]//g")
user=$(id -u -n) # Instead using $USER variable which can be overwrite
host=$(uname -n) # Same like user variable, it also can be overwrite
pkgs=$(
    case $(uname -s) in
        (Linux*)
            has dpkg && dpkg-query -W
            has xbps-query && xbps-query -l
            has pacman-key && pacman -Qq
            has rpm && rpm -qa
            has dnf && dnf list installed
            has apk && apk info
            has guix && guix package --list-installed
            has opkg && opkg list-installed
        ;;
        (*)
            # 0 pkgs
        ;;
    esac | wc -l
)
bar_len=${#host}+${#user}+1
bar=$(
    for ((i = 0; i < $bar_len; i++)); do
        echo -n "-";
    done
)
color_head=
color_logo=
color_info=
color_end="\033[0m"
case $1 in
    (-ra)
        color_head="\033[0;$(shuf -i 31-38 -n 1)m"
        color_logo="\033[0;$(shuf -i 31-38 -n 1)m"
        color_info="\033[0;$(shuf -i 31-38 -n 1)m"
    ;;
    (-rb)
        color_head="\033[1;$(shuf -i 31-38 -n 1)m"
        color_logo="\033[1;$(shuf -i 31-38 -n 1)m"
        color_info="\033[1;$(shuf -i 31-38 -n 1)m"
    ;;
    (-b)
        color_head="\033[1;5m"
        color_logo="\033[1;5m"
        color_info="\033[1;5m"
    ;;
    (-h)
        help
        exit
    ;;
esac

echo -ne "
                 $color_head$user@$host$color_end
                 $color_head$bar$color_end
    $color_logo/\_/\  ($color_end    $color_info os: $os$color_end
   $color_logo( ^.^ ) _)$color_end   $color_info kernel: $kernel_ver$color_end
     $color_logo/|\ ($color_end      $color_info wm: $wm$color_end
   $color_logo( | | )$color_end      $color_info shell: ${SHELL##*/}$color_end
  $color_logo(__d b__)$color_end     $color_info pkgs: $pkgs$color_end
                $color_info uptime: $uptime$color_end

"
